# Generated by Django 4.0.4 on 2022-05-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0004_alter_employee_personal_details_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_personal_details',
            name='contact_num',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='employee_personal_details',
            name='emp_age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='employee_personal_details',
            name='emp_salary',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
