# Generated by Django 4.0.4 on 2022-05-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'employee_app',
            '0005_alter_employee_personal_details_contact_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_personal_details',
            name='contact_num',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee_personal_details',
            name='emp_age',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee_personal_details',
            name='emp_salary',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee_personal_details',
            name='employee_id',
            field=models.CharField(max_length=100),
        ),
    ]
