# Generated by Django 4.0.4 on 2022-05-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'employee_app',
            '0006_alter_employee_personal_details_contact_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_information',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('about_self', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employee_details',
            name='created_at',
        ),
    ]
