# Generated by Django 4.0.4 on 2022-05-09 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0007_employee_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
