# Generated by Django 4.0.4 on 2022-05-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0008_employee_details_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_information',
            name='about_self',
        ),
        migrations.RemoveField(
            model_name='employee_information',
            name='age',
        ),
        migrations.RemoveField(
            model_name='employee_information',
            name='salary',
        ),
    ]
